### ISSUE TITLE
Changing port in docker? v2

### ISSUE THREAD

**Issue by ZippoD** [manbearwiz/youtube-dl-server#165]
Hi,
So there was a case already for this question, but the resolution was to re-map the container port (8080) to a different port on the host, which is not the same thing. That doesn't work when containers are routed thru another container network (e.g. VPN), because port mapping needs to be done by the VPN container (and when there is more than one container requiring 8080 there is a conflict). 
Any way to actually change the web port from default 8080 to something else?

**Comment by JBlond** [comment]
You can use the ports

```yaml
version: "3.9"
services:
  youtube-dl:
    image: "kmb32123/youtube-dl-server"
    network_mode: "service:vpn"
    volumes:
      - ./down:/youtube-dl
    restart: unless-stopped
    ports:
      - "99:8080"
  ```
