### ISSUE TITLE
Background processes / automated jobs (e.g. "subscribing" to a playlist to be constantly queried for new videos

### ISSUE THREAD

**Issue by GlassedSilver** [manbearwiz/youtube-dl-server#41]
Would love if I could have a docker that's both a manual downloader for one-off videos as well as defining criteria for what to watch for new content on a constant basis.

This would be especially helpful in one single yt-dl instance because then the archive.txt that stores already downloaded videos would skip duplicates. :)

**Comment by manbearwiz** [comment]
I do this now using flexget combined with youtube-dl. You can have flexget subscribe and filter to content and then post the URL to the API exposed by youtube-dl.

**Comment by GlassedSilver** [comment]
Does youtube-dl within this docker keep an archive.txt?

And what are its default options? I would love for metadata to be embedded and put into a separate file for example amongst other things like customizing the filename and path logic to automate importing into Plex and generally just having clean metadata independent of Plex' database...

Overall the documentation about the default behavior is a bit lukewarm...

**Comment by JunNineKim** [comment]
I want to try to do this one which you mentioned "I do this now using flexget combined with youtube-dl. You can have flexget subscribe and filter to content and then post the URL to the API exposed by youtube-dl."
Could you describe that one more detail?, I will try to do it.

**Comment by manbearwiz** [comment]
Here is a flexget task that subscribes to the rss feed for the official YouTube Music channel and sends new entries to the youtube-dl server for download. You should just have to change the curl url to point to your youtube-dl instance, and change the playlist_id to any channel you want.

```
tasks:
  get-youtubemusic:
    priority: 4
    rss:
      url: https://www.youtube.com/feeds/videos.xml?playlist_id=PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI
    accept_all: yes
    exec:
      auto_escape: yes
      on_output:
        for_accepted: 'curl -X POST --data-urlencode "url={{url}}" http://web/youtube-dl/q'
```
