### ISSUE TITLE
Changing port in docker?

### ISSUE THREAD

**Issue by gerroon** [manbearwiz/youtube-dl-server#47]
Hi

I am using docker line to run it. How can IO change the default port?

thanks

**Comment by brunoamaral** [comment]
I was testing this using docker-compose and changed the port by mapping it in the ports section. I am using 7123 as an example. Make sure you are using python3.

```yaml
version: '2.2'

services:
  youtube-dl:
    image: "kmb32123/youtube-dl-server"
    container_name: youtube-dl
    command: 'python3 -u ./youtube-dl-server.py'
    restart: always
    ports:
      - 7123:7123
    networks:
      - traefik_proxy
    volumes:
      - /mnt/hdd/Videos:/youtube-dl
    environment:
      - YDL_SERVER_PORT=7123
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.youtube-dl.tls=true"
      # - "traefik.http.routers.youtube-dl.midddlewares=stsheaders"
      - "traefik.http.services.youtube-dl.loadbalancer.server.port=7123"
      - "traefik.http.routers.youtube-dl.rule=Host(`${DOMAIN_NAME_2}`) && PathPrefix(`/youtube-dl`)"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```
