### ISSUE TITLE
Build for ARM

### ISSUE THREAD

**Issue by offbyone** [manbearwiz/youtube-dl-server#69]
Hola, thanks for a cool tool!

I'd like to run this on my Raspberry Pi in your docker container; is there any chance you could enable ARM builds for it on dockerhub?

**Comment by fl0r1s** [comment]
You can build it straight from the repo in your compose file
```
  youtube-dl: 
    image: kmb32123/youtube-dl-server
    container_name: youtube-dl
    build: https://www.github.com/manbearwiz/youtube-dl-server.git
    environment: 
      - UID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - YDL_SERVER_PORT=${YOUTUBE_DL_PORT}
    volumes:
      - ${MEDIA_ROOT}/downloads:/youtube-dl
    ports: 
      - "${YOUTUBE_DL_PORT}:${YOUTUBE_DL_PORT}"
    restart: unless-stopped
```

and run `docker-compose build youtube-dl`. However this version did not work on my system and I moved to the nbr23 fork [here](https://github.com/nbr23/youtube-dl-server).
